const useStyles = {
  root: {
    display: "flex",
    margin: {
      xs: "120px 0px 0px 0px",
      sm: "25px 0px 0px 0px",
      md: "25px 0px 0px 0px",
    },
    flexDirection: "column",
    gap: "10px",
    justifyContent: "center",
    alignItems: "center",
  },
  containerGrid: {
    marginTop: "15px",
    boxShadow: "8px 8px 8px 0px black",
    maxWidth: { xs: "350px", sm: "400px", md: "500px" },
    width: "100%",
  },
  gridItem: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "65px",
    fontWeight: "bold",
    height: { xs: "100px", sm: "125px", md: "150px" },
    transition: "0.3s all ease-out",
    "&:hover": {
      transition: "0.2s all ease-in",
      opacity: "0.6",
      cursor: "pointer",
    },
  },
  containerHome: {
    margin: {
      xs: "100px 0px 0px 0px",
      sm: "150px 0px 0px 0px",
      md: "200px 0px 0px 0px",
    },
    width: "100%",
    maxWidth: "600px",
    height: "250px",
    borderRadius: "10px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "25px",
    gap: "1rem",
    backgroundColor: "#BEBEBE",
    boxShadow:"6px 4px 4px 0px black"
  },
  containerSettings: {
    margin: "2.5px 5px",
    width: "100%",
    maxWidth: "300px",
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
  },
  containerInfo: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "50px",
    width: "300px",
    padding: "10px",
    borderRadius: "15px",
    boxShadow: "5px 5px 5px 0px black",
    background: "#BEBEBE ",
    backgroundImage: "#BEBEBE",
    transition: "0.5ms all ease-in",
  },
  Typography: {
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 17,
  },
};

export { useStyles };
